### ISSUE TITLE
Report a problem button

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#11]
**Is your feature request related to a problem? ❓**
This feature is not related to any kind of problems; But, it would be great if the feature get to be added.

**Describe the solution you'd like 📃**
As you can see in the image at the footer of the page there is a red button saying report a problem.
The red text is only meant for highlighting only the real thing can be white and blend in with other buttons.

The "report a problem" button should link to the Timetables' GitHub issue page.
(https://github.com/SS-Developers/Timetables/issues) 

<img width="1440" alt="Screen Shot 2565-05-09 at 09 26 03" src="https://user-images.githubusercontent.com/90727258/167330366-51814662-1255-4f98-9d44-fa8042f7a294.png">

**Comment by Jiraties** [comment]
Thanks for suggesting 🎉, This feature is implemented and will be pushed into production soon.
