### ISSUE TITLE
Course name overlapping with the icon

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#12]
**Describe the bug 🔎**
Is this bug a logical or visual (CSS) one? How is this bug affecting the experience?

This is a visual bug at "At a glance". the name is overlapping with the icon.

**To Reproduce 🧪**
Clear steps on how to reproduce this bug/behavior

Have a long course name example "English A / Second Language". with a 13" display (common)

**Expected behavior 🔥**
What is expected to happen instead of a bug

The course name should not overlap with the icon.

**Screenshot 🖼️ (optional)**
A screenshot of the website or the console
<img width="549" alt="Screen Shot 2565-05-10 at 09 21 54" src="https://user-images.githubusercontent.com/90727258/167529645-72b9095e-b8d3-4e09-af72-433356057fe1.png">

**Comment by Jiraties** [comment]
This issue has been resolved. Expect this issue to be gone in the next production update.
