### ISSUE TITLE
Overflowing hover-view

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#14]
## **Describe the bug 🔎**

How is this bug affecting the experience

This is a visual bug the modal-like thing that display when click or hold touch overflow outside of the page boundary.

## **To Reproduce 🧪**

Clear steps on how to reproduce this bug / behavior

Click or hold on the period with long name. 
Example: Student Development Activity, others

## **Expected behavior 🔥**

What is expected to happen instead of a bug

The modal should only overflow outside the timetable boundary.

## **Screenshot 🖼️ (optional)**
![image](https://user-images.githubusercontent.com/90727258/168709422-4eb34b6a-d4ba-4362-9c59-0c285b08e1f4.png)

**Comment by Jiraties** [comment]
Thanks for the issue, The issue will be fixed when the next major update (v4) releases. 
Your report has led us to overcome the following issue by re-designing the way the expanded view pops out 

![image](https://user-images.githubusercontent.com/87472782/196732310-5288fe26-c74f-4088-886d-d6fb5c97e4c9.png)
