### ISSUE TITLE
Error for new users with no primary classes

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#2]
Error Code : 
![Screenshot_20220405_182543](https://user-images.githubusercontent.com/90727258/161743989-5cede61d-abb6-4cf4-a888-c8dade98d5d5.png)

Back end returned :
![Screenshot_20220405_182727](https://user-images.githubusercontent.com/90727258/161744208-058999ad-f091-4227-9fe8-4bd98e373bb1.png)

**Comment by Jiraties** [comment]
Thanks for bug reporting. The issue has been resolved by redirecting the user to the setup page instantly when the program sees that the user doesn't have a primaryClass.
