### ISSUE TITLE
Add a sorting/filtering button

### ISSUE THREAD

**Issue by chickennnn** [Alt-Developers/Timetables#3]
I request a sorting/filtering button that sorts/filters one's school from another. The location should be around the star that I marked in the photo below here.

  ![image](https://user-images.githubusercontent.com/91784022/161798672-a81b48b9-b5dd-41b5-9cad-729982387e77.png)

**Comment by Jiraties** [comment]
Working on it!

**Comment by chickennnn** [comment]
looking forward to it :D

**Comment by Jiraties** [comment]
This feature has been successfully made! You can expect to see this feature in the upcoming releases.
Thanks for suggesting 😁

![image](https://user-images.githubusercontent.com/87472782/162711791-4b96ff7a-2995-406a-9596-de16adf466b6.png)

**Comment by prawich-th** [comment]
if the timetable is getting too much maybe I should add the pagination support for SS APIs (Timetable API).

what do you think? @Jiraties
