### ISSUE TITLE
Setup screen not displaying

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#5]
**Describe the bug 🔎**
Is this bug a logical or visual (CSS) one. How is this bug affecting the experience

**To Reproduce 🧪**
Clear steps on how to reproduce this bug / behavior

?

**Expected behavior 🔥**
What is expected to happen instead of a bug

It should be a setup page.

**Screenshot 🖼️ (optional)**
A screenshot of the website or the console
![Screenshot_20220413_062244](https://user-images.githubusercontent.com/90727258/163070332-10051a67-49dc-466f-9e93-eab736afa507.png)

**Comment by Jiraties** [comment]
Please be more in-depth about the description and provide more context. The issue will be closed due to a lack of information.
