### ISSUE TITLE
Setup Screen displaying when it shouldn't be.

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#6]
**Describe the bug 🔎**
Is this bug a logical or visual (CSS) one. How is this bug affecting the experience

setup screen displaying for an account that already have a primary class.

**To Reproduce 🧪**
Clear steps on how to reproduce this bug / behavior

come from the central authentication.

**Expected behavior 🔥**
What is expected to happen instead of a bug

not display the setup screen, display the main page.

**Screenshot 🖼️ (optional)**
A screenshot of the website or the console
![Screenshot_20220413_063027](https://user-images.githubusercontent.com/90727258/163071033-dcd0a9d5-43a4-489d-accf-8a2dcf7f0295.png)

**Comment by Jiraties** [comment]
Thanks for reporting!

This bug was caused due to the front-end not implementing the new feature from Timetables in Central Authentication and now it should be fixed!
