### ISSUE TITLE
Clock displays seconds

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#7]
**Describe the bug 🔎**
Is this bug a logical or visual (CSS) one. How is this bug affecting the experience

**To Reproduce 🧪**
Clear steps on how to reproduce this bug / behavior

**Expected behavior 🔥**
What is expected to happen instead of a bug

**Screenshot 🖼️ (optional)**
A screenshot of the website or the console
<img width="676" alt="Screen Shot 2565-04-18 at 09 29 40" src="https://user-images.githubusercontent.com/90727258/163745093-0097f0be-611b-407b-b663-483f4c494ff3.png">

**Comment by Jiraties** [comment]
The seconds on the clock isn't a bug, It's a feature

**Comment by prawich-th** [comment]
I know but it only display **00** all the time
