### ISSUE TITLE
Refresher not working.

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/Timetables#8]
**Describe the bug 🔎**
Is this bug a logical or visual (CSS) one. How is this bug affecting the experience

the refresher didn't work when it suppose to (does not work at all).

**To Reproduce 🧪**
Clear steps on how to reproduce this bug / behavior

**Expected behavior 🔥**
What is expected to happen instead of a bug

The refresher should refresh the glace module.

**Screenshot 🖼️ (optional)**
A screenshot of the website or the console
![Timetable issue 1](https://user-images.githubusercontent.com/90727258/166104905-6196226a-ad7c-40ce-8f6a-48f6c2ed487a.png)

**Comment by Jiraties** [comment]
The following bug has been resolved.
